name: "Set up environment"

description: "Install and setup tools and libs"

inputs:
   qiniuAK:
     required: true
     description: "qiniu access key"
   qiniuSK:
     required: true
     description: "qiniu secret key"
   qiniuAccount:
     required: false
     description: "qiniu account name"

runs:
  using: "composite"
  steps:
    # node.js
    - name: Set up node 16.14.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
    
    # python2
    - name: Set up python 2.7 
      uses: actions/setup-python@v4
      with:
        python-version: 2.7 

    # python3
    - name: Set up python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # msbuild
    - name: Set up msbuild 15.9
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 15.9

    # install deps
    - name: Install dependences
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install libbluetooth-dev

    # cache qshell tool
    - name: Cache qshell
      id: cache-qshell-win
      uses: actions/cache@v3
      with:
        path: ./qshell.exe
        key: ${{runner.os}}-qshell

    # download qshell
    - name: Download qshell
      if: steps.cache-qshell-win.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: powershell
      run: |
        Invoke-RestMethod -Uri 'https://devtools.qiniu.com/qshell-v2.9.2-windows-386.zip' -OutFile 'qshell.zip'
        Expand-Archive -LiteralPath qshell.zip -DestinationPath ./
    
    # setup qshell
    - name: Setup qshell
      run: ./qshell account ${{inputs.qiniuAK}} ${{inputs.qiniuSK}} ${{inputs.qiniuAccount}}
      shell: bash

