name: "Set up environment"

description: "Install and setup tools and libs"

runs:
  using: "composite"
  steps:
    # node.js
    - name: Set up node 16.14.2
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
    
    # python2
    - name: Set up python 2.7 
      uses: actions/setup-python@v4
      with:
        python-version: 2.7 

    # python3
    - name: Set up python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - run: echo ${{runner.os}}

    # msbuild
    - name: Set up msbuild 15.9
      if: runner.os == 'windows'
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 15.9

