name: "Update Server Variable"

description: "update server variable"

inputs:
   secret:
     required: true
     description: "request secret"
   version:
     required: true
     description: "package version"

runs:
  using: "composite"
  steps:
    # update server variables
    - name: Update release time
      shell: powershell
      run: >
        curl --location --request POST 'https://bittly.sigechen.com/deploy/set-variable' 
        --form 'key="windows_released_at"' 
        --form "value=$(date '+%Y-%m-%d')" 
        --form 'secret="${{inputs.secret}}"' -s

    # update server variables
    - name: Update release version
      shell: powershell
      run: >
        curl --location --request POST 'https://bittly.sigechen.com/deploy/set-variable' 
        --form 'key="windows_released_version"' 
        --form "value=$env:appver" 
        --form 'secret="${{inputs.secret}}"' -s
      env:
        appver: ${{inputs.version}}

    # update server variables
    - name: Update release size for ia32
      shell: powershell
      run: >
        curl --location --request POST 'https://bittly.sigechen.com/deploy/set-variable' 
        --form 'key="windows_released_size_exe_x86"' 
        --form "value=$([Math]::Truncate((Get-Item -Path ./dist_electron/bittly-$env:appver-win-ia32.exe).Length/1MB*100)/100)MB" 
        --form 'secret="${{inputs.secret}}"' -s
      env:
        appver: ${{inputs.version}}

    # update server variables
    - name: Update release size for x64
      shell: powershell
      run: >
        curl --location --request POST 'https://bittly.sigechen.com/deploy/set-variable' 
        --form 'key="windows_released_size_exe_x64"' 
        --form "value=$([Math]::Truncate((Get-Item -Path ./dist_electron/bittly-$env:appver-win-x64.exe).Length/1MB*100)/100)MB" 
        --form 'secret="${{inputs.secret}}"' -s
      env:
        appver: ${{inputs.version}}

