name: Build Test Package

# @link : https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on: 
  workflow_dispatch:
    inputs:
      packey:
        description: 'the key to generate package name'
        required: true
        type: string

jobs:
  # build windows package for testing
  build-window-packages:
    runs-on: windows-2022
    steps:
      # node.js
      - name: Set up node 16.19.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
      
      # python2
      - name: Set up python 2.7
        uses: actions/setup-python@v4
        with:
          python-version: 2.7 

      # python3
      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      # msbuild
      - name: Set up msbuild 15.9
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 15.9

      # checkout 
      - name: Checkout repository
        uses: actions/checkout@v1

      # get version
      - name: Read package version
        id: package-json
        uses: Saionaro/extract-package-version@v1.0.6
      
      # install
      - name: Install dependences
        run: npm install --python=python2.7

      # build
      - name: Build app package
        run: npm run electron:build -- --x64
