name: Build Test Package

# @link : https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on: workflow_dispatch

jobs:
  # build windows package for testing
  build-window-packages:
    runs-on: windows-2022
    steps:
      # # node.js
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.14.2
      
      # # python2
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: 2.7 

      # # python3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.11
      
      # # msbuild
      # - uses: microsoft/setup-msbuild@v1.1
      #   with:
      #     vs-version: 15.9

      # checkout 
      # - uses: actions/checkout@v1

      # - name: Read version
      #   id: read-version
      #   run: >
      #     $version = (Get-Content -Encoding UTF8 .\package.json | ConvertFrom-Json).version ;
      #     echo "version=$version" >> $GITHUB_OUTPUT ;
      #     echo "version=$version" ;

      - name: Read version
        id: read-version
        run: echo "version=123" >> $GITHUB_OUTPUT

      # # install
      # - run: npm install --python=python2.7

      # # build
      # - run: npm run electron:build -- --x64

      - run: echo VERSION = [$sss] ---- [${{steps.read-version.outputs.version}}]
        env:
          sss: "xxxx"

      # # setup qshell and upload package to cdn
      # - run: Invoke-RestMethod -Uri 'https://devtools.qiniu.com/qshell-v2.9.2-windows-386.zip' -OutFile 'qshell.zip'
      # - run: Expand-Archive -LiteralPath qshell.zip -DestinationPath ./
      # - run: ./qshell account ${{secrets.QINIU_AK}} ${{secrets.QINIU_SK}} ${{secrets.QINIU_ACCOUNT_NAME}}
      # - run: >
      #     ./qshell fput ${{secrets.QINIU_BUCKET_TEST}} bittly/bittly-${VERSION}-x64-test.exe 
      #     ./dist_electron/bittly-${VERSION}-win-x64.exe 
      #   env:
      #     VERSION: ${{steps.package-json.outputs.version}}