name: Build App

on: push

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.14.2
        architecture: x64
    - run: npm install
    - run: npm run electron:build
