name: Build App

on: push

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libbluetooth-dev
    - run: python --version
    - run: python2 --version
    - run: python3 --version
    - uses: actions/checkout@v1
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.14.2
        architecture: x64
    # - run: npm install
    # - run: npm run electron:build
