name: Build App

on: push

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install python2
    - run: sudo apt-get install libbluetooth-dev
    - uses: actions/checkout@v1
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.14.2
        architecture: x64
    - run: npm install --python=python2.7
    - run: npm run electron:build
    - run: cd dist_electron && tree
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - run: echo ${{steps.package-version.outputs.current-version}}
    # - run: wget https://devtools.qiniu.com/qshell-v2.9.2-linux-386.tar.gz
    # - run: tar -zxvf qshell-v2.9.2-linux-386.tar.gz
    # - run: chmod u+x qshell
    # - run: ./qshell --version
    # - run: ./qshell account ${{secrets.QINIU_AK}} ${{secrets.QINIU_SK}} ${{secrets.QINIU_ACCOUNT_NAME}}
    # - run: echo fput ${{secrets.QINIU_BUCKET}} download/${{steps.package-version.outputs.current-version}}/bittly-${{steps.package-version.outputs.current-version}}-x64.AppImage ./dist_electron/bittly-${{steps.package-version.outputs.current-version}}-x64.AppImage

